// Auto-generated by tools/license.mjs init - the license PUBLIC key.
// Safe to ship; only the private key (gitignored) can sign.
export const LICENSE_PUBLIC_JWK = {
  "kty": "EC",
  "x": "dJ8Nbx4r1VInlI87vJmnkuCDLcRuOv_ijVos5tzhHWM",
  "y": "fjBKKF6UwTNJ2mWFRTn4ZUPwLUjSQ4POo6xP3687teg",
  "crv": "P-256"
};
