// Auto-generated by tools/license.mjs init - the license PUBLIC key.
// Safe to ship; only the private key (gitignored) can sign.
export const LICENSE_PUBLIC_JWK = {
  "kty": "EC",
  "x": "t6VjZDOG3v7kd0_nYfgwVMquu0WnWFAempGho_6HSsw",
  "y": "QZeS07B885BQWSnkU4Ub9PQBK6bc1mGnPi6K-UdnNgQ",
  "crv": "P-256"
};
